### ISSUE TITLE
部署vercel报错

### ISSUE THREAD

**Issue by maotuworkroom** [weekend-project-space/tv-online#1]
如题

**Comment by weekend-project-space** [comment]
错误信息是啥

**Comment by maotuworkroom** [comment]
> 错误信息是啥

![image](https://github.com/weekend-project-space/tv-online/assets/37393495/48c0889b-56bd-4461-b2c8-925044232393)

**Comment by weekend-project-space** [comment]
video.js 这个依赖没找到，额

本地可以
```
npm install
npm run build
```
一下

然后把打包好的内容新建一个仓库部署
